export const CssProperty = {
    background: "background",
    opacity: "opacity",
    boxShadow: "box-shadow",
    padding: "padding",
    paddingTop: "padding-top",
    paddingBottom: "padding-bottom",
    paddingLeft: "padding-left",
    paddingRight: "padding-right",
    margin: "margin",
    marginRight: "margin-right",
    marginTop: "margin-top",
    marginBottom: "margin-bottom",
    marginLeft: "margin-left",
    position: "position",
    border: "border",
    borderTop: "border-top",
    borderLeft: "border-left",
    borderRight: "border-right",
    borderBottom: "border-bottom",
    borderRadius: "border-radius",
    display: "display",
    flexDirection: "flex-direction",
    alignItems: "align-items",
    justifyContent: "justify-content",
    gap: "gap",
    width: "width",
    minWidth: "min-width",
    maxWidth: "max-width",
    height: "height",
    minHeight: "min-height",
    maxHeight: "max-height",
    overFlow: "overFlow",
    color: "color",
    fontSize: "font-size",
    fontWeight: "font-weight",
    wordBreak: "word-break",
    textOverflow: "text-overflow",
    cursor: "cursor",
    lineHeight: "line-height",
    textAlign: "text-align",
    top: "top",
    left: "left",
    right: "right",
    bottom: "bottom",
    transitionDelay: "transition-delay",
    transitionDuration: "transition-duration",
    transition: "transition",
    transform: "transform",
    transformOrigin: "transform-origin",
    zIndex: "z-index",
    overflow: "overflow",
    overflowX: "overflow-x",
    overflowY: "overflow-y",
    whiteSpace: "white-space",
    wordWrap: "word-wrap",
    textIndent: "text-indent",
    textTransform: "text-transform",
    textDecoration: "text-decoration",
    listStyle: "list-style",
    listStyleType: "list-style-type",
    listStylePosition: "list-style-position",
    listStyleImage: "list-style-image",
    objectFit: "object-fit",
    objectPosition: "object-position",
    fill: "fill",
    stroke: "stroke",
    strokeWidth: "stroke-width",
    strokeDasharray: "stroke-dasharray",
    strokeDashoffset: "stroke-dashoffset",
    strokeLinecap: "stroke-linecap",
    strokeLinejoin: "stroke-linejoin",
    strokeMiterlimit: "stroke-miterlimit",
    strokeOpacity: "stroke-opacity",
    fillOpacity: "fill-opacity",
    fillRule: "fill-rule",
    clipPath: "clip-path",
    clipRule: "clip-rule",
    mask: "mask",
    maskType: "mask-type",
    maskUnits: "mask-units",
    maskPosition: "mask-position",
    maskImage: "mask-image",
    maskOrigin: "mask-origin",
    maskSize: "mask-size",
    maskComposite: "mask-composite",
    maskClip: "mask-clip",
    maskMode: "mask-mode",
    maskRepeat: "mask-repeat",
    maskOffset: "mask-offset",
    maskUnits: "mask-units",
    pointerEvents: "pointer-events"
}

/**
 * @param {typeof CssProperty} object 
 */
export const s = (object) => {
    return Object.keys(object).map((k)=> {
        const [key, value] = [k, object[k]]
        if (CssProperty[key])
            return `${CssProperty[key]}: ${value}`
        return `${k}: ${value}`
    }).join(";")
}